name: opencode

on:
  issue_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: [created, edited]
  workflow_dispatch:

jobs:
  opencode:
    if: |
      github.event_name == 'workflow_dispatch' ||
      startsWith(github.event.comment.body, '/oc') ||
      startsWith(github.event.comment.body, '/opencode') ||
      contains(github.event.comment.body, ' /oc') ||
      contains(github.event.comment.body, ' /opencode') ||
      contains(github.event.comment.body, '\n/oc') ||
      contains(github.event.comment.body, '\n/opencode')
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Run opencode
        uses: anomalyco/opencode/github@v1.14.31
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STEPFUN_API_KEY: ${{ secrets.STEPFUN_API_KEY }}
        with:
          model: stepfun/step-3.5-flash-2603
          share: false
          use_github_token: true
